######################################################################
#
# File name : sim_pairhmm_top_tb_simulate.do
# Created on: Mon Apr 15 11:05:13 CEST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib xil_defaultlib sim_pairhmm_top_tb_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

view wave
view structure
view signals

run 1000ns
