######################################################################
#
# File name : sim_pairhmm_top_tb_compile.do
# Created on: Mon Apr 15 11:05:01 CEST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../ip/bd/compute_unit/ipshared/0ab1/hdl" "+incdir+../../design" "+incdir+/PATH/TO/VIVADO/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../ip/ip/result_fifo/sim/result_fifo.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../ip/bd/compute_unit/ip/compute_unit_add_0_0/sim/compute_unit_add_0_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_add_1_0/sim/compute_unit_add_1_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_add_2_0/sim/compute_unit_add_2_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_add_3_0/sim/compute_unit_add_3_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_add_4_0/sim/compute_unit_add_4_0.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../ip/bd/compute_unit/ipshared/0ab1/hdl" "+incdir+../../design" "+incdir+/PATH/TO/VIVADO/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../ip/bd/compute_unit/ip/compute_unit_axis_data_fifo_0_0/sim/compute_unit_axis_data_fifo_0_0.v" \
"../../ip/bd/compute_unit/ip/compute_unit_axis_data_fifo_1_0/sim/compute_unit_axis_data_fifo_1_0.v" \
"../../ip/bd/compute_unit/ip/compute_unit_axis_data_fifo_2_0/sim/compute_unit_axis_data_fifo_2_0.v" \
"../../ip/bd/compute_unit/ip/compute_unit_axis_data_fifo_3_0/sim/compute_unit_axis_data_fifo_3_0.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../ip/bd/compute_unit/ip/compute_unit_mul_0_0/sim/compute_unit_mul_0_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_1_0/sim/compute_unit_mul_1_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_2_0/sim/compute_unit_mul_2_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_3_0/sim/compute_unit_mul_3_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_4_0/sim/compute_unit_mul_4_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_5_0/sim/compute_unit_mul_5_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_mul_6_0/sim/compute_unit_mul_6_0.vhd" \
"../../ip/bd/compute_unit/ip/compute_unit_sub_0_0/sim/compute_unit_sub_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../ip/bd/compute_unit/ipshared/0ab1/hdl" "+incdir+../../design" "+incdir+/PATH/TO/VIVADO/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../ip/bd/compute_unit/sim/compute_unit.v" \
"../../ip/ip/worker_bram/sim/worker_bram.v" \
"../../ip/ip/job_log_bram/sim/job_log_bram.v"

vcom -64 -93 -work xil_defaultlib  \
"../../ip/bd/floating_point_sum/ip/floating_point_sum_floating_point_sum_0_0/sim/floating_point_sum_floating_point_sum_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  "+incdir+../../ip/bd/compute_unit/ipshared/0ab1/hdl" "+incdir+../../design" "+incdir+/PATH/TO/VIVADO/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../ip/bd/floating_point_sum/sim/floating_point_sum.v" \
"../../ip/ip/bram_32b_x_2048/sim/bram_32b_x_2048.v" \
"../../ip/ip/bram_11b_x_2048/sim/bram_11b_x_2048.v" \
"../../ip/bd/compute_unit/hdl/compute_unit_wrapper.v" \
"../../ip/bd/floating_point_sum/hdl/floating_point_sum_wrapper.v" \

vlog -64 -incr -sv -L xil_defaultlib -work xil_defaultlib  "+incdir+../../ip/bd/compute_unit/ipshared/0ab1/hdl" "+incdir+../../design" "+incdir+/PATH/TO/VIVADO/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../design/cl_axi_read_arbiter.sv" \
"../../design/cl_compute_engine_wrapper.sv" \
"../../design/cl_compute_result_combiner.sv" \
"../../design/cl_workgroup_controller.sv" \
"../../design/cl_pairhmm_workgroup.sv" \
"../../design/cl_pairhmm_worker_stream.sv" \
"../../design/cl_pairhmm_new_worker_core_synth.sv" \
"../../design/cl_main_controller.sv" \
"../../design/cl_compute_stream_separator.sv" \
"../../design/cl_conveyer.sv" \
"../../design/cl_conveyer_axi_s.sv" \
"../../design/cl_interfaces.sv" \
"../../design/cl_debug_interfaces.sv" \
"../../design/cl_matrix_crawler.sv" \
"../../design/cl_job_logger.sv" \
"../../design/cl_write_back.sv" \
"../../design/cl_pairhmm_top.sv" \
"../../sim/sim_axi_slave_memory.sv" \
"../../sim/sim_pairhmm_top_tb.sv"