######################################################################
#
# File name : sim_pairhmm_top_tb_elaborate.do
# Created on: Mon Apr 15 11:05:02 CEST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -L fifo_generator_v13_2_1 -L xil_defaultlib -L xbip_utils_v3_0_8 -L axi_utils_v2_0_4 -L xbip_pipe_v3_0_4 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_dsp48_addsub_v3_0_4 -L xbip_dsp48_multadd_v3_0_4 -L xbip_bram18k_v3_0_4 -L mult_gen_v12_0_13 -L floating_point_v7_1_5 -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v1_1_16 -L blk_mem_gen_v8_4_1 -L blk_mem_gen_v8_4_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.sim_pairhmm_top_tb -o sim_pairhmm_top_tb_opt
